# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/helpboarddb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:helpboard_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:6be8bd2f76a42943672db310bfaf65d4b328b557ea680b01fef7b40dfad34ead}
# 1 hour = 3600000 milliseconds
jwt.expirationMs=${JWT_EXPIRATIONMS:3600000}

# Server Port
server.port=${SERVER_PORT:8080}

# CORS Configuration
spring.web.cors.allowed-origins=${SPRING_CORS_ALLOWED_ORIGINS:http://localhost:3000}